// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.java.smartOffice;

public interface deadlineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deadlineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectName = 1;</code>
   */
  java.lang.String getProjectName();
  /**
   * <code>string projectName = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();
}
