// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.java.smartOffice;

public interface deadlineReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deadlineReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectTime = 1;</code>
   */
  java.lang.String getProjectTime();
  /**
   * <code>string projectTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectTimeBytes();
}
