// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.java.smartOffice;

public interface deskReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deskReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deskBooked = 1;</code>
   */
  java.lang.String getDeskBooked();
  /**
   * <code>string deskBooked = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeskBookedBytes();
}
