// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.java.smartOffice;

public interface deskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bookDesk = 1;</code>
   */
  int getBookDesk();
}
