// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.java.smartOffice;

public final class DeskBookingServiceImpl {
  private DeskBookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deskReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deskReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\" \n\014loginRequest\022\020\n\010user" +
      "name\030\001 \001(\t\"\037\n\013deskRequest\022\020\n\010bookDesk\030\001 " +
      "\001(\005\"\037\n\tdeskReply\022\022\n\ndeskBooked\030\001 \001(\t2f\n\013" +
      "DeskBooking\022/\n\013portalLogin\022\r.loginReques" +
      "t\032\r.loginRequest\"\000(\001\022&\n\010bookDesk\022\014.deskR" +
      "equest\032\n.deskReply\"\000B/\n\023ds.java.smartOff" +
      "iceB\026DeskBookingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_loginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_deskRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deskRequest_descriptor,
        new java.lang.String[] { "BookDesk", });
    internal_static_deskReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_deskReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deskReply_descriptor,
        new java.lang.String[] { "DeskBooked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
