// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface doorReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string success = 1;</code>
   */
  java.lang.String getSuccess();
  /**
   * <code>string success = 1;</code>
   */
  com.google.protobuf.ByteString
      getSuccessBytes();
}
