// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface doorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 passCode = 1;</code>
   */
  int getPassCode();
}
