// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface doorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string passCode = 1;</code>
   */
  java.lang.String getPassCode();
  /**
   * <code>string passCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getPassCodeBytes();
}
