// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface lightReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stayOn = 1;</code>
   */
  java.lang.String getStayOn();
  /**
   * <code>string stayOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getStayOnBytes();

  /**
   * <code>string turnOff = 2;</code>
   */
  java.lang.String getTurnOff();
  /**
   * <code>string turnOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getTurnOffBytes();
}
