// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface lightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lights = 1;</code>
   */
  java.lang.String getLights();
  /**
   * <code>string lights = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightsBytes();
}
