// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface lightReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightState = 1;</code>
   */
  java.lang.String getLightState();
  /**
   * <code>string lightState = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightStateBytes();
}
