// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

/**
 * Protobuf type {@code lightReply}
 */
public  final class lightReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightReply)
    lightReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lightReply.newBuilder() to construct.
  private lightReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lightReply() {
    stayOn_ = "";
    turnOff_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lightReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stayOn_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            turnOff_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.java.smartOffice.RoomControllerServiceImpl.internal_static_lightReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.java.smartOffice.RoomControllerServiceImpl.internal_static_lightReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.java.smartOffice.lightReply.class, ds.java.smartOffice.lightReply.Builder.class);
  }

  public static final int STAYON_FIELD_NUMBER = 1;
  private volatile java.lang.Object stayOn_;
  /**
   * <code>string stayOn = 1;</code>
   */
  public java.lang.String getStayOn() {
    java.lang.Object ref = stayOn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stayOn_ = s;
      return s;
    }
  }
  /**
   * <code>string stayOn = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStayOnBytes() {
    java.lang.Object ref = stayOn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stayOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TURNOFF_FIELD_NUMBER = 2;
  private volatile java.lang.Object turnOff_;
  /**
   * <code>string turnOff = 2;</code>
   */
  public java.lang.String getTurnOff() {
    java.lang.Object ref = turnOff_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      turnOff_ = s;
      return s;
    }
  }
  /**
   * <code>string turnOff = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTurnOffBytes() {
    java.lang.Object ref = turnOff_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      turnOff_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStayOnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stayOn_);
    }
    if (!getTurnOffBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, turnOff_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStayOnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stayOn_);
    }
    if (!getTurnOffBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, turnOff_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.java.smartOffice.lightReply)) {
      return super.equals(obj);
    }
    ds.java.smartOffice.lightReply other = (ds.java.smartOffice.lightReply) obj;

    boolean result = true;
    result = result && getStayOn()
        .equals(other.getStayOn());
    result = result && getTurnOff()
        .equals(other.getTurnOff());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STAYON_FIELD_NUMBER;
    hash = (53 * hash) + getStayOn().hashCode();
    hash = (37 * hash) + TURNOFF_FIELD_NUMBER;
    hash = (53 * hash) + getTurnOff().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.java.smartOffice.lightReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.java.smartOffice.lightReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.java.smartOffice.lightReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.java.smartOffice.lightReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.java.smartOffice.lightReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.java.smartOffice.lightReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.java.smartOffice.lightReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightReply)
      ds.java.smartOffice.lightReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.java.smartOffice.RoomControllerServiceImpl.internal_static_lightReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.java.smartOffice.RoomControllerServiceImpl.internal_static_lightReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.java.smartOffice.lightReply.class, ds.java.smartOffice.lightReply.Builder.class);
    }

    // Construct using ds.java.smartOffice.lightReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stayOn_ = "";

      turnOff_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.java.smartOffice.RoomControllerServiceImpl.internal_static_lightReply_descriptor;
    }

    @java.lang.Override
    public ds.java.smartOffice.lightReply getDefaultInstanceForType() {
      return ds.java.smartOffice.lightReply.getDefaultInstance();
    }

    @java.lang.Override
    public ds.java.smartOffice.lightReply build() {
      ds.java.smartOffice.lightReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.java.smartOffice.lightReply buildPartial() {
      ds.java.smartOffice.lightReply result = new ds.java.smartOffice.lightReply(this);
      result.stayOn_ = stayOn_;
      result.turnOff_ = turnOff_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.java.smartOffice.lightReply) {
        return mergeFrom((ds.java.smartOffice.lightReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.java.smartOffice.lightReply other) {
      if (other == ds.java.smartOffice.lightReply.getDefaultInstance()) return this;
      if (!other.getStayOn().isEmpty()) {
        stayOn_ = other.stayOn_;
        onChanged();
      }
      if (!other.getTurnOff().isEmpty()) {
        turnOff_ = other.turnOff_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.java.smartOffice.lightReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.java.smartOffice.lightReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stayOn_ = "";
    /**
     * <code>string stayOn = 1;</code>
     */
    public java.lang.String getStayOn() {
      java.lang.Object ref = stayOn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stayOn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stayOn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStayOnBytes() {
      java.lang.Object ref = stayOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stayOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stayOn = 1;</code>
     */
    public Builder setStayOn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stayOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stayOn = 1;</code>
     */
    public Builder clearStayOn() {
      
      stayOn_ = getDefaultInstance().getStayOn();
      onChanged();
      return this;
    }
    /**
     * <code>string stayOn = 1;</code>
     */
    public Builder setStayOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stayOn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object turnOff_ = "";
    /**
     * <code>string turnOff = 2;</code>
     */
    public java.lang.String getTurnOff() {
      java.lang.Object ref = turnOff_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        turnOff_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string turnOff = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTurnOffBytes() {
      java.lang.Object ref = turnOff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        turnOff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string turnOff = 2;</code>
     */
    public Builder setTurnOff(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      turnOff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string turnOff = 2;</code>
     */
    public Builder clearTurnOff() {
      
      turnOff_ = getDefaultInstance().getTurnOff();
      onChanged();
      return this;
    }
    /**
     * <code>string turnOff = 2;</code>
     */
    public Builder setTurnOffBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      turnOff_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lightReply)
  }

  // @@protoc_insertion_point(class_scope:lightReply)
  private static final ds.java.smartOffice.lightReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.java.smartOffice.lightReply();
  }

  public static ds.java.smartOffice.lightReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lightReply>
      PARSER = new com.google.protobuf.AbstractParser<lightReply>() {
    @java.lang.Override
    public lightReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lightReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lightReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lightReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.java.smartOffice.lightReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

