// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.java.smartOffice;

public interface loginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
