// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.java.smartOffice;

public final class ProjectManagementServiceImpl {
  private ProjectManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deadlineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deadlineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deadlineReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deadlineReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stateReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stateReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\"&\n\017deadlineRequest\022\023\n\013p" +
      "rojectName\030\001 \001(\t\"$\n\rdeadlineReply\022\023\n\013pro" +
      "jectTime\030\001 \001(\t\"(\n\014stateRequest\022\030\n\020projec" +
      "tNameState\030\001 \001(\t\"%\n\nstateReply\022\027\n\017projec" +
      "tComplete\030\001 \001(\t2q\n\021ProjectManagement\0220\n\010" +
      "deadline\022\020.deadlineRequest\032\016.deadlineRep" +
      "ly\"\000(\001\022*\n\ncheckState\022\r.stateRequest\032\013.st" +
      "ateReply\"\000B5\n\023ds.java.smartOfficeB\034Proje" +
      "ctManagementServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_deadlineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_deadlineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deadlineRequest_descriptor,
        new java.lang.String[] { "ProjectName", });
    internal_static_deadlineReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deadlineReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deadlineReply_descriptor,
        new java.lang.String[] { "ProjectTime", });
    internal_static_stateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stateRequest_descriptor,
        new java.lang.String[] { "ProjectNameState", });
    internal_static_stateReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stateReply_descriptor,
        new java.lang.String[] { "ProjectComplete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
