// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.java.smartOffice;

public interface stateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectNameState = 1;</code>
   */
  java.lang.String getProjectNameState();
  /**
   * <code>string projectNameState = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNameStateBytes();
}
