// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.java.smartOffice;

public interface stateReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stateReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectComplete = 1;</code>
   */
  java.lang.String getProjectComplete();
  /**
   * <code>string projectComplete = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectCompleteBytes();
}
