// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface tempReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tempReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tempResult1 = 1;</code>
   */
  int getTempResult1();

  /**
   * <code>string tempResult2 = 2;</code>
   */
  java.lang.String getTempResult2();
  /**
   * <code>string tempResult2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getTempResult2Bytes();
}
