// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface tempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temp = 1;</code>
   */
  double getTemp();
}
