// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface tempReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tempReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempResult = 1;</code>
   */
  java.lang.String getTempResult();
  /**
   * <code>string tempResult = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempResultBytes();
}
