// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.java.smartOffice;

public interface tempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp1 = 1;</code>
   */
  int getTemp1();

  /**
   * <code>string temp2 = 2;</code>
   */
  java.lang.String getTemp2();
  /**
   * <code>string temp2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemp2Bytes();
}
